//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 05:12:13 PM CET 
//


package tim9.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import tim9.xml.model.Clan;;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pravniOsnov">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://parlament.gov.rs/propis}Clan"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nazivPredlogaPropisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recAmandman" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="predlogPropisa" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element ref="{http://parlament.gov.rs/amandman}odredba"/>
 *                   &lt;element ref="{http://parlament.gov.rs/amandman}predlozenoResenje"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="obrazlozenje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="razlogPodnosenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="objasnjenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cilj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="procenaUticaja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="potpis" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pravniOsnov",
    "nazivPredlogaPropisa",
    "recAmandman",
    "predlogPropisa",
    "obrazlozenje"
})
@XmlRootElement(name = "Amandman")
public class Amandman {

    @XmlElement(required = true)
    protected Amandman.PravniOsnov pravniOsnov;
    @XmlElement(required = true)
    protected String nazivPredlogaPropisa;
    @XmlElement(required = true, defaultValue = "AMANDMAN")
    protected List<Amandman.RecAmandman> recAmandman;
    @XmlElement(required = true)
    protected List<Amandman.PredlogPropisa> predlogPropisa;
    @XmlElement(required = true)
    protected Amandman.Obrazlozenje obrazlozenje;
    @XmlAttribute(name = "potpis")
    @XmlSchemaType(name = "anySimpleType")
    protected String potpis;

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.PravniOsnov }
     *     
     */
    public Amandman.PravniOsnov getPravniOsnov() {
        return pravniOsnov;
    }

    /**
     * Sets the value of the pravniOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.PravniOsnov }
     *     
     */
    public void setPravniOsnov(Amandman.PravniOsnov value) {
        this.pravniOsnov = value;
    }

    /**
     * Gets the value of the nazivPredlogaPropisa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPredlogaPropisa() {
        return nazivPredlogaPropisa;
    }

    /**
     * Sets the value of the nazivPredlogaPropisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPredlogaPropisa(String value) {
        this.nazivPredlogaPropisa = value;
    }

    /**
     * Gets the value of the recAmandman property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recAmandman property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecAmandman().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Amandman.RecAmandman }
     * 
     * 
     */
    public List<Amandman.RecAmandman> getRecAmandman() {
        if (recAmandman == null) {
            recAmandman = new ArrayList<Amandman.RecAmandman>();
        }
        return this.recAmandman;
    }

    /**
     * Gets the value of the predlogPropisa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the predlogPropisa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPredlogPropisa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Amandman.PredlogPropisa }
     * 
     * 
     */
    public List<Amandman.PredlogPropisa> getPredlogPropisa() {
        if (predlogPropisa == null) {
            predlogPropisa = new ArrayList<Amandman.PredlogPropisa>();
        }
        return this.predlogPropisa;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link Amandman.Obrazlozenje }
     *     
     */
    public Amandman.Obrazlozenje getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amandman.Obrazlozenje }
     *     
     */
    public void setObrazlozenje(Amandman.Obrazlozenje value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="razlogPodnosenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="objasnjenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cilj" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="procenaUticaja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "razlogPodnosenja",
        "objasnjenje",
        "cilj",
        "procenaUticaja"
    })
    public static class Obrazlozenje {

        @XmlElement(required = true)
        protected String razlogPodnosenja;
        @XmlElement(required = true)
        protected String objasnjenje;
        @XmlElement(required = true)
        protected String cilj;
        @XmlElement(required = true)
        protected String procenaUticaja;

        /**
         * Gets the value of the razlogPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazlogPodnosenja() {
            return razlogPodnosenja;
        }

        /**
         * Sets the value of the razlogPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazlogPodnosenja(String value) {
            this.razlogPodnosenja = value;
        }

        /**
         * Gets the value of the objasnjenje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjasnjenje() {
            return objasnjenje;
        }

        /**
         * Sets the value of the objasnjenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjasnjenje(String value) {
            this.objasnjenje = value;
        }

        /**
         * Gets the value of the cilj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCilj() {
            return cilj;
        }

        /**
         * Sets the value of the cilj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCilj(String value) {
            this.cilj = value;
        }

        /**
         * Gets the value of the procenaUticaja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcenaUticaja() {
            return procenaUticaja;
        }

        /**
         * Sets the value of the procenaUticaja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcenaUticaja(String value) {
            this.procenaUticaja = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://parlament.gov.rs/propis}Clan"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clan"
    })
    public static class PravniOsnov {

        @XmlElement(name = "Clan", namespace = "http://parlament.gov.rs/propis", required = true)
        protected Clan clan;

        /**
         * Gets the value of the clan property.
         * 
         * @return
         *     possible object is
         *     {@link Clan }
         *     
         */
        public Clan getClan() {
            return clan;
        }

        /**
         * Sets the value of the clan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Clan }
         *     
         */
        public void setClan(Clan value) {
            this.clan = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element ref="{http://parlament.gov.rs/amandman}odredba"/>
     *         &lt;element ref="{http://parlament.gov.rs/amandman}predlozenoResenje"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "odredbaAndPredlozenoResenje"
    })
    public static class PredlogPropisa {

        @XmlElements({
            @XmlElement(name = "odredba", required = true, type = Odredba.class),
            @XmlElement(name = "predlozenoResenje", required = true, type = PredlozenoResenje.class)
        })
        protected List<Object> odredbaAndPredlozenoResenje;

        /**
         * Gets the value of the odredbaAndPredlozenoResenje property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the odredbaAndPredlozenoResenje property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOdredbaAndPredlozenoResenje().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Odredba }
         * {@link PredlozenoResenje }
         * 
         * 
         */
        public List<Object> getOdredbaAndPredlozenoResenje() {
            if (odredbaAndPredlozenoResenje == null) {
                odredbaAndPredlozenoResenje = new ArrayList<Object>();
            }
            return this.odredbaAndPredlozenoResenje;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="redniBroj" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class RecAmandman {

        @XmlValue
        protected String content;
        @XmlAttribute(name = "redniBroj")
        @XmlSchemaType(name = "anySimpleType")
        protected String redniBroj;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the redniBroj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRedniBroj() {
            return redniBroj;
        }

        /**
         * Sets the value of the redniBroj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRedniBroj(String value) {
            this.redniBroj = value;
        }

    }

}
