//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 04:28:27 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://parlament.gov.rs/propis", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tim9.xml.model;
