//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.21 at 09:12:04 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tim9.com/korisnik", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tim9.xml.model.korisnik;
