//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 10:30:36 PM CEST 
//


package tim9.xml.model.amandman;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tim9.amandman package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OdredbaAkta_QNAME = new QName("http://www.tim9.com/amandman", "OdredbaAkta");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tim9.amandman
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Preambula }
     * 
     */
    public Preambula createPreambula() {
        return new Preambula();
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link Preambula.Status }
     * 
     */
    public Preambula.Status createPreambulaStatus() {
        return new Preambula.Status();
    }

    /**
     * Create an instance of {@link Preambula.DatumPredaje }
     * 
     */
    public Preambula.DatumPredaje createPreambulaDatumPredaje() {
        return new Preambula.DatumPredaje();
    }

    /**
     * Create an instance of {@link Preambula.DatumObjave }
     * 
     */
    public Preambula.DatumObjave createPreambulaDatumObjave() {
        return new Preambula.DatumObjave();
    }

    /**
     * Create an instance of {@link Preambula.BrojGlasovaZa }
     * 
     */
    public Preambula.BrojGlasovaZa createPreambulaBrojGlasovaZa() {
        return new Preambula.BrojGlasovaZa();
    }

    /**
     * Create an instance of {@link Preambula.BrojGlasovaProtiv }
     * 
     */
    public Preambula.BrojGlasovaProtiv createPreambulaBrojGlasovaProtiv() {
        return new Preambula.BrojGlasovaProtiv();
    }

    /**
     * Create an instance of {@link Preambula.BrojGlasovaUzdrzano }
     * 
     */
    public Preambula.BrojGlasovaUzdrzano createPreambulaBrojGlasovaUzdrzano() {
        return new Preambula.BrojGlasovaUzdrzano();
    }

    /**
     * Create an instance of {@link Sadrzaj }
     * 
     */
    public Sadrzaj createSadrzaj() {
        return new Sadrzaj();
    }

    /**
     * Create an instance of {@link Obrazlozenje }
     * 
     */
    public Obrazlozenje createObrazlozenje() {
        return new Obrazlozenje();
    }

    /**
     * Create an instance of {@link Predlog }
     * 
     */
    public Predlog createPredlog() {
        return new Predlog();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tim9.com/amandman", name = "OdredbaAkta")
    public JAXBElement<String> createOdredbaAkta(String value) {
        return new JAXBElement<String>(_OdredbaAkta_QNAME, String.class, null, value);
    }

}
