//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.21 at 09:12:04 PM CEST 
//


package tim9.xml.model.sednica;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import tim9.xml.model.akt.Akt;
import tim9.xml.model.amandman.Amandman;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrojPrisutnih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.tim9.com/akt}Akt"/>
 *           &lt;element ref="{http://www.tim9.com/amandman}Amandman"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datum",
    "status",
    "brojPrisutnih",
    "aktOrAmandman"
})
@XmlRootElement(name = "Sednica")
public class Sednica {

    @XmlElement(name = "Datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "BrojPrisutnih")
    protected int brojPrisutnih;
    @XmlElements({
        @XmlElement(name = "Akt", namespace = "http://www.tim9.com/akt", type = Akt.class),
        @XmlElement(name = "Amandman", namespace = "http://www.tim9.com/amandman", type = Amandman.class)
    })
    protected List<Object> aktOrAmandman;
    @XmlAttribute(name = "Id")
    @XmlSchemaType(name = "anySimpleType")
    protected Integer id;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the brojPrisutnih property.
     * 
     */
    public int getBrojPrisutnih() {
        return brojPrisutnih;
    }

    /**
     * Sets the value of the brojPrisutnih property.
     * 
     */
    public void setBrojPrisutnih(int value) {
        this.brojPrisutnih = value;
    }

    /**
     * Gets the value of the aktOrAmandman property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aktOrAmandman property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAktOrAmandman().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Akt }
     * {@link Amandman }
     * 
     * 
     */
    public List<Object> getAktOrAmandman() {
        if (aktOrAmandman == null) {
            aktOrAmandman = new ArrayList<Object>();
        }
        return this.aktOrAmandman;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

	@Override
	public String toString() {
		return "Sednica [datum=" + datum + ", status=" + status + ", brojPrisutnih=" + brojPrisutnih
				+ ", aktOrAmandman=" + aktOrAmandman + ", id=" + id + "]";
	}
    

}
